development:
  adapter: postgresql
  encoding: unicode
  database: db/carbonbase_development
  host: localhost
  pool: 5
  username: denis
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: db/carbonbase_test
  host: localhost
  pool: 5
  username: denis
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: db/carbonbase_production
  pool: 5
  username: denis
  password:
