require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WebcrawlsController do

  # This should return the minimal set of attributes required to create a valid
  # Webcrawl. As you add validations to Webcrawl, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WebcrawlsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all webcrawls as @webcrawls" do
      webcrawl = Webcrawl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:webcrawls).should eq([webcrawl])
    end
  end

  describe "GET show" do
    it "assigns the requested webcrawl as @webcrawl" do
      webcrawl = Webcrawl.create! valid_attributes
      get :show, {:id => webcrawl.to_param}, valid_session
      assigns(:webcrawl).should eq(webcrawl)
    end
  end

  describe "GET new" do
    it "assigns a new webcrawl as @webcrawl" do
      get :new, {}, valid_session
      assigns(:webcrawl).should be_a_new(Webcrawl)
    end
  end

  describe "GET edit" do
    it "assigns the requested webcrawl as @webcrawl" do
      webcrawl = Webcrawl.create! valid_attributes
      get :edit, {:id => webcrawl.to_param}, valid_session
      assigns(:webcrawl).should eq(webcrawl)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Webcrawl" do
        expect {
          post :create, {:webcrawl => valid_attributes}, valid_session
        }.to change(Webcrawl, :count).by(1)
      end

      it "assigns a newly created webcrawl as @webcrawl" do
        post :create, {:webcrawl => valid_attributes}, valid_session
        assigns(:webcrawl).should be_a(Webcrawl)
        assigns(:webcrawl).should be_persisted
      end

      it "redirects to the created webcrawl" do
        post :create, {:webcrawl => valid_attributes}, valid_session
        response.should redirect_to(Webcrawl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved webcrawl as @webcrawl" do
        # Trigger the behavior that occurs when invalid params are submitted
        Webcrawl.any_instance.stub(:save).and_return(false)
        post :create, {:webcrawl => {}}, valid_session
        assigns(:webcrawl).should be_a_new(Webcrawl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Webcrawl.any_instance.stub(:save).and_return(false)
        post :create, {:webcrawl => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested webcrawl" do
        webcrawl = Webcrawl.create! valid_attributes
        # Assuming there are no other webcrawls in the database, this
        # specifies that the Webcrawl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Webcrawl.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => webcrawl.to_param, :webcrawl => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested webcrawl as @webcrawl" do
        webcrawl = Webcrawl.create! valid_attributes
        put :update, {:id => webcrawl.to_param, :webcrawl => valid_attributes}, valid_session
        assigns(:webcrawl).should eq(webcrawl)
      end

      it "redirects to the webcrawl" do
        webcrawl = Webcrawl.create! valid_attributes
        put :update, {:id => webcrawl.to_param, :webcrawl => valid_attributes}, valid_session
        response.should redirect_to(webcrawl)
      end
    end

    describe "with invalid params" do
      it "assigns the webcrawl as @webcrawl" do
        webcrawl = Webcrawl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Webcrawl.any_instance.stub(:save).and_return(false)
        put :update, {:id => webcrawl.to_param, :webcrawl => {}}, valid_session
        assigns(:webcrawl).should eq(webcrawl)
      end

      it "re-renders the 'edit' template" do
        webcrawl = Webcrawl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Webcrawl.any_instance.stub(:save).and_return(false)
        put :update, {:id => webcrawl.to_param, :webcrawl => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested webcrawl" do
      webcrawl = Webcrawl.create! valid_attributes
      expect {
        delete :destroy, {:id => webcrawl.to_param}, valid_session
      }.to change(Webcrawl, :count).by(-1)
    end

    it "redirects to the webcrawls list" do
      webcrawl = Webcrawl.create! valid_attributes
      delete :destroy, {:id => webcrawl.to_param}, valid_session
      response.should redirect_to(webcrawls_url)
    end
  end

end
