require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WhenDatesController do

  # This should return the minimal set of attributes required to create a valid
  # WhenDate. As you add validations to WhenDate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WhenDatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all when_dates as @when_dates" do
      when_date = WhenDate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:when_dates).should eq([when_date])
    end
  end

  describe "GET show" do
    it "assigns the requested when_date as @when_date" do
      when_date = WhenDate.create! valid_attributes
      get :show, {:id => when_date.to_param}, valid_session
      assigns(:when_date).should eq(when_date)
    end
  end

  describe "GET new" do
    it "assigns a new when_date as @when_date" do
      get :new, {}, valid_session
      assigns(:when_date).should be_a_new(WhenDate)
    end
  end

  describe "GET edit" do
    it "assigns the requested when_date as @when_date" do
      when_date = WhenDate.create! valid_attributes
      get :edit, {:id => when_date.to_param}, valid_session
      assigns(:when_date).should eq(when_date)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WhenDate" do
        expect {
          post :create, {:when_date => valid_attributes}, valid_session
        }.to change(WhenDate, :count).by(1)
      end

      it "assigns a newly created when_date as @when_date" do
        post :create, {:when_date => valid_attributes}, valid_session
        assigns(:when_date).should be_a(WhenDate)
        assigns(:when_date).should be_persisted
      end

      it "redirects to the created when_date" do
        post :create, {:when_date => valid_attributes}, valid_session
        response.should redirect_to(WhenDate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved when_date as @when_date" do
        # Trigger the behavior that occurs when invalid params are submitted
        WhenDate.any_instance.stub(:save).and_return(false)
        post :create, {:when_date => {}}, valid_session
        assigns(:when_date).should be_a_new(WhenDate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WhenDate.any_instance.stub(:save).and_return(false)
        post :create, {:when_date => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested when_date" do
        when_date = WhenDate.create! valid_attributes
        # Assuming there are no other when_dates in the database, this
        # specifies that the WhenDate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WhenDate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => when_date.to_param, :when_date => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested when_date as @when_date" do
        when_date = WhenDate.create! valid_attributes
        put :update, {:id => when_date.to_param, :when_date => valid_attributes}, valid_session
        assigns(:when_date).should eq(when_date)
      end

      it "redirects to the when_date" do
        when_date = WhenDate.create! valid_attributes
        put :update, {:id => when_date.to_param, :when_date => valid_attributes}, valid_session
        response.should redirect_to(when_date)
      end
    end

    describe "with invalid params" do
      it "assigns the when_date as @when_date" do
        when_date = WhenDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WhenDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => when_date.to_param, :when_date => {}}, valid_session
        assigns(:when_date).should eq(when_date)
      end

      it "re-renders the 'edit' template" do
        when_date = WhenDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WhenDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => when_date.to_param, :when_date => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested when_date" do
      when_date = WhenDate.create! valid_attributes
      expect {
        delete :destroy, {:id => when_date.to_param}, valid_session
      }.to change(WhenDate, :count).by(-1)
    end

    it "redirects to the when_dates list" do
      when_date = WhenDate.create! valid_attributes
      delete :destroy, {:id => when_date.to_param}, valid_session
      response.should redirect_to(when_dates_url)
    end
  end

end
